version: '3.5'
services:
  mysql:
    container_name: d3n15micro
    image: mysql:8.0
    command: --max_allowed_packet=1073741824 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=userdb
      - MYSQL_ROOT_PASSWORD=xxx
    ports:
      - 3306:3306
    volumes:
      - ./backup.sql:/backupuserdb.sql
