version: '3.8'
services:
  mysql:
    container_name: d3n15micro
    image: mysql:8.0
    command: --max_allowed_packet=1073741824 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=userdb
      - MYSQL_ROOT_PASSWORD=eusou100
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: eusou100
      MONGO_INITDB_DATABASE: pedidodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/pedidodb

volumes:
  mysql_data:
  mongo_data:
