server:
  port: 8761

spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: d3n15-tec-eureka-user
      password: d3n15123456789

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false