server:
#  port: 0
  port: 9094

eureka:
  client:
    service-url:
      defaultZone: http://d3n15-tec-eureka-user:d3n15123456789@localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      host: localhost
      port: 27017
      database: pedidodb
      authentication-database: admin
      username: admin
      password: eusou100
