server:
  # port: 0
  port: 9093

eureka:
  client:
    service-url:
      defaultZone: http://d3n15-tec-eureka-user:d3n15123456789@localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?useTimezone=true&serverTimezone=UTC
    username: root
    password: eusou100
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 604800000  # 180000 3 minutos
      refresh-token:
        expiration: 604800000 # 360000 6 min ---604800000 7 days
